name: moveeasy_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  http: ^1.2.0
  shared_preferences: ^2.3.0
  gtfs_realtime_bindings: ^1.0.0
  flutter_secure_storage: ^9.0.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  geolocator: ^14.0.2
  flutter_local_notifications: ^19.5.0
  awesome_dialog: ^3.2.0
  vibration: ^3.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/stop.png
    - assets/icons/bus.png

dependency_overrides:
  path_provider_foundation: 2.4.0